quarkus.profile=dev
quarkus.http.port=8080

quarkus.devservices.enabled=false

quarkus.smallrye-openapi.info-title=Lumio
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Lumio - Learn Brighter. Go Further.
quarkus.smallrye-openapi.info-terms-of-service=https://lumio.com/terms
quarkus.smallrye-openapi.info-contact-email=support@lumio.com
quarkus.smallrye-openapi.info-contact-name=Lumio Team
quarkus.smallrye-openapi.info-contact-url=https://lumio.com
quarkus.smallrye-openapi.info-license-name=Apache 2.0
quarkus.smallrye-openapi.info-license-url=https://www.apache.org/licenses/LICENSE-2.0.htmlache.org/licenses/LICENSE-2.0.html

quarkus.smallrye-openapi.security-scheme=jwt
quarkus.smallrye-openapi.security-scheme-name=security
quarkus.smallrye-openapi.security-scheme-description=Insert Bearer Token Valid


#quarkus.log.console.enabled=true 
#quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{3.}] (%t) %s%e%n
#quarkus.log.console.level=INFO