quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=${AWS_ACCESS_KEY}
quarkus.s3.aws.credentials.static-provider.secret-access-key=${AWS_SECRET_KEY}
quarkus.s3.endpoint-override=${AWS_ENDPOINT}
quarkus.s3.aws.region=${AWS_REGION}

quarkus.sqs.aws.credentials.type=static
quarkus.sqs.aws.credentials.static-provider.access-key-id=${AWS_ACCESS_KEY}
quarkus.sqs.aws.credentials.static-provider.secret-access-key=${AWS_SECRET_KEY}
quarkus.sqs.aws.region=${AWS_REGION}
quarkus.sqs.endpoint-override=${AWS_ENDPOINT}
aws.sqs.queue.url=${AWS_SQS_QUEUE_URL}

quarkus.datasource.jdbc.url=${POSTGRES_LOCAL_URL}
quarkus.datasource.jdbc.max-size=16
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_LOCAL_USERNAME}
quarkus.datasource.password=${POSTGRES_LOCAL_PASSWORD}


quarkus.oidc.auth-server-url=${OIDC_AUTH_SERVER}
quarkus.oidc.client-id=${OIDC_CLIENT_ID}
quarkus.oidc.credentials.secret=${OIDC_CREDENTIALS_SECRET}
quarkus.oidc.application-type=${OIDC_APPLICATION_TYPE}

quarkus.mailer.host=${MAILER_HOST}
quarkus.mailer.port=${MAILER_PORT}
quarkus.mailer.from=${MAILER_FROM}
quarkus.mailer.mock=false

quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/metrics

quarkus.cache.enabled=true