quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=${AWS_ACCESS_KEY}
quarkus.s3.aws.credentials.static-provider.secret-access-key=${AWS_SECRET_KEY}
quarkus.s3.endpoint-override=${AWS_ENDPOINT}
quarkus.s3.aws.region=${AWS_REGION}

rabbitmq-host=${RABBIT_HOST}
rabbitmq-port=${RABBIT_PORT}
rabbitmq-username=${RABBIT_USER}
rabbitmq-password=${RABBIT_PASS}

mp.messaging.incoming.user-create-in.runOnVirtualThread=true
mp.messaging.incoming.video-upload-in.runOnVirtualThread=true
mp.messaging.incoming.resource-upload-in.runOnVirtualThread=true
mp.messaging.incoming.user-notifiable-in.runOnVirtualThread=true

mp.messaging.incoming.user-create-in.retry-attempts=3
mp.messaging.incoming.resource-upload-in.retry-attempts=3
mp.messaging.incoming.video-upload-in.retry-attempts=3
mp.messaging.incoming.user-notifiable-in.retry-attempts=3

mp.messaging.outgoing.user-create-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.user-create-out.exchange.name=${USER_CREATE_EXCHANGE}
mp.messaging.outgoing.user-create-out.queue.name=${USER_CREATE_QUEUE}
mp.messaging.outgoing.user-create-out.auto-bind=true

mp.messaging.incoming.user-create-in.connector=smallrye-rabbitmq
mp.messaging.incoming.user-create-in.queue.name=${USER_CREATE_QUEUE}
mp.messaging.incoming.user-create-in.auto-bind=true

mp.messaging.outgoing.video-upload-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.video-upload-out.exchange.name=${VIDEO_UPLOAD_EXCHANGE}
mp.messaging.outgoing.video-upload-out.queue.name=${VIDEO_UPLOAD_QUEUE}
mp.messaging.outgoing.video-upload-out.auto-bind=true

mp.messaging.incoming.video-upload-in.connector=smallrye-rabbitmq
mp.messaging.incoming.video-upload-in.queue.name=${VIDEO_UPLOAD_QUEUE}
mp.messaging.incoming.video-upload-in.auto-bind=true

mp.messaging.outgoing.resource-upload-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.resource-upload-out.exchange.name=${RESOURCE_UPLOAD_EXCHANGE}
mp.messaging.outgoing.resource-upload-out.queue.name=${RESOURCE_UPLOAD_QUEUE}
mp.messaging.outgoing.resource-upload-out.auto-bind=true

mp.messaging.incoming.resource-upload-in.connector=smallrye-rabbitmq
mp.messaging.incoming.resource-upload-in.queue.name=${RESOURCE_UPLOAD_QUEUE}
mp.messaging.incoming.resource-upload-in.auto-bind=true

mp.messaging.outgoing.user-notifiable-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.user-notifiable-out.exchange.name=${USER_EVENTS_EXCHANGE}
mp.messaging.outgoing.user-notifiable-out.exchange.type=topic
mp.messaging.outgoing.user-notifiable-out.routing-key=user.created.success

mp.messaging.incoming.user-notifiable-in.connector=smallrye-rabbitmq
mp.messaging.incoming.user-notifiable-in.exchange.name=${USER_EVENTS_EXCHANGE}
mp.messaging.incoming.user-notifiable-in.exchange.type=topic
mp.messaging.incoming.user-notifiable-in.queue.name=${USER_NOTIFICATIONS_QUEUE}
mp.messaging.incoming.user-notifiable-in.routing-key=user.created.success
mp.messaging.incoming.user-notifiable-in.auto-bind=true

quarkus.datasource.jdbc.url=${POSTGRES_LOCAL_URL}
quarkus.datasource.jdbc.max-size=16
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.datasource.username=${POSTGRES_LOCAL_USERNAME}
quarkus.datasource.password=${POSTGRES_LOCAL_PASSWORD}

quarkus.oidc.auth-server-url=${OIDC_AUTH_SERVER}
quarkus.oidc.client-id=${OIDC_CLIENT_ID}
quarkus.oidc.credentials.secret=${OIDC_CREDENTIALS_SECRET}
quarkus.oidc.application-type=${OIDC_APPLICATION_TYPE}

keycloak-admin/mp-rest/url=${KEYCLOAK_ADMIN_URL}
keycloak-admin/mp-rest/connectTimeout=${KEYCLOAK_CONNECT_TIMEOUT}
keycloak-admin/mp-rest/readTimeout=${KEYCLOAK_READ_TIMEOUT}

keycloak-token/mp-rest/url=${KEYCLOAK_AUTH_URL}
keycloak-token/mp-rest/connectTimeout=${KEYCLOAK_CONNECT_TIMEOUT}
keycloak-token/mp-rest/readTimeout=${KEYCLOAK_READ_TIMEOUT}

brasilapi/mp-rest/url=${BRASILAPI_URL}
brasilapi/mp-rest/connectTimeout=${BRASILAPI_CONNECT_TIMEOUT}
brasilapi/mp-rest/readTimeout=${BRASILAPI_READ_TIMEOUT}

keycloak.realm=${KEYCLOAK_REALM} 
keycloak.client-id=${KEYCLOAK_CLIENT_ID}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}

quarkus.mailer.host=${MAILER_HOST}
quarkus.mailer.port=${MAILER_PORT}
quarkus.mailer.from=${MAILER_FROM}
quarkus.mailer.mock=false

quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/metrics
quarkus.micrometer.binder.http-server.enabled=false

quarkus.cache.enabled=true
quarkus.cache.caffeine."keycloak-token".expire-after-write=290s

mp.fault.tolerance.enabled=true
mp.fault.tolerance.timeout.value=5000
mp.fault.tolerance.retry.maxRetries=3
mp.fault.tolerance.retry.delay=500

mp.fault.tolerance.circuitbreaker.requestVolumeThreshold=10
mp.fault.tolerance.circuitbreaker.failureRatio=0.5
mp.fault.tolerance.circuitbreaker.delay=30000