quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=${AWS_ACCESS_KEY}
quarkus.s3.aws.credentials.static-provider.secret-access-key=${AWS_SECRET_KEY}
quarkus.s3.endpoint-override=${AWS_ENDPOINT}
quarkus.s3.aws.region=${AWS_REGION}

quarkus.sqs.aws.credentials.type=static
quarkus.sqs.aws.credentials.static-provider.access-key-id=${AWS_ACCESS_KEY}
quarkus.sqs.aws.credentials.static-provider.secret-access-key=${AWS_SECRET_KEY}
quarkus.sqs.aws.region=${AWS_REGION}
quarkus.sqs.endpoint-override=${AWS_ENDPOINT}

aws.sqs.queue.video-upload=${VIDEO_UPLOAD_QUEUE_URL}
aws.sqs.queue.video-dlq=${VIDEO_DLQ_QUEUE_URL}
aws.sqs.queue.resource-upload=${RESOURCE_UPLOAD_QUEUE_URL}
aws.sqs.queue.resource-dlq=${RESOURCE_DLQ_QUEUE_URL}
aws.sqs.queue.keycloak-user-create=${KEYCLOAK_USER_CREATE_QUEUE_URL}
aws.sqs.queue.keycloak-user-create-dlq=${KEYCLOAK_USER_CREATE_DLQ_URL}

aws.sqs.health.queues=${VIDEO_UPLOAD_QUEUE_URL},${RESOURCE_UPLOAD_QUEUE_URL},${KEYCLOAK_USER_CREATE_QUEUE_URL}

quarkus.datasource.jdbc.url=${POSTGRES_LOCAL_URL}
quarkus.datasource.jdbc.max-size=16
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.datasource.username=${POSTGRES_LOCAL_USERNAME}
quarkus.datasource.password=${POSTGRES_LOCAL_PASSWORD}

quarkus.oidc.auth-server-url=${OIDC_AUTH_SERVER}
quarkus.oidc.client-id=${OIDC_CLIENT_ID}
quarkus.oidc.credentials.secret=${OIDC_CREDENTIALS_SECRET}
quarkus.oidc.application-type=${OIDC_APPLICATION_TYPE}

keycloak-admin/mp-rest/url=${KEYCLOAK_ADMIN_URL}
keycloak-admin/mp-rest/connectTimeout=${KEYCLOAK_CONNECT_TIMEOUT}
keycloak-admin/mp-rest/readTimeout=${KEYCLOAK_READ_TIMEOUT}

keycloak-token/mp-rest/url=${KEYCLOAK_AUTH_URL}
keycloak-token/mp-rest/connectTimeout=${KEYCLOAK_CONNECT_TIMEOUT}
keycloak-token/mp-rest/readTimeout=${KEYCLOAK_READ_TIMEOUT}

brasilapi/mp-rest/url=${BRASILAPI_URL}
brasilapi/mp-rest/connectTimeout=${BRASILAPI_CONNECT_TIMEOUT}
brasilapi/mp-rest/readTimeout=${BRASILAPI_READ_TIMEOUT}

keycloak.realm=${KEYCLOAK_REALM} 
keycloak.client-id=${KEYCLOAK_CLIENT_ID}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}

quarkus.mailer.host=${MAILER_HOST}
quarkus.mailer.port=${MAILER_PORT}
quarkus.mailer.from=${MAILER_FROM}
quarkus.mailer.mock=false

quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/metrics
quarkus.micrometer.binder.jvm.enabled=false
quarkus.micrometer.binder.http-server.enabled=false
quarkus.micrometer.binder.system.enabled=false

quarkus.cache.enabled=true
quarkus.cache.caffeine."keycloak-token".expire-after-write=290s

mp.fault.tolerance.enabled=true
mp.fault.tolerance.timeout.value=5000
mp.fault.tolerance.retry.maxRetries=3
mp.fault.tolerance.retry.delay=500

mp.fault.tolerance.circuitbreaker.requestVolumeThreshold=10
mp.fault.tolerance.circuitbreaker.failureRatio=0.5
mp.fault.tolerance.circuitbreaker.delay=30000